# Generated by Django 3.1.7 on 2021-02-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_price',
        ),
    ]
